name=sgp4
version=1.0
author=Daniel Warner
maintainer=Daniel Warner <contact@danrw.com>
sentence=SGP4 tracking library
paragraph=Simplified perturbations model 4 propagater.
category=Data Processing
url=https://github.com/dnwrnr/sgp4
architectures=avr,megaavr,sam,samd,nrf52,stm32f4,mbed,mbed_nano,mbed_portenta,mbed_rp2040,renesas,renesas_portenta,renesas_uno,esp8266,esp32
dot_a_linkage=true
